export const HOME = '/'
export const ANIME_PAGE = '/anime/:slug'
export const FAVOURITE = '/favourite'
export const PROFILE = '/profile'
export const LOGIN = '/login'
export const REGISTER = '/register'
